from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("http://practice.automationtesting.in/")
driver.execute_script("window.scrollBy(0, 600);")
driver.find_element_by_css_selector(".post-160 h3").click()
driver.find_element_by_css_selector('[href="#tab-reviews"]').click()
driver.find_element_by_css_selector('.star-5').click()
review = driver.find_element_by_id('comment')
review.send_keys("Nice book")
name = driver.find_element_by_id('author')
name.send_keys("Tony Stark")
email = driver.find_element_by_id('email')
email.send_keys("starkindustries@mail.com")
driver.find_element_by_css_selector('.submit').click()
driver.quit()